template: home
title: Accueil
meta:
  description: Restaurant et take-away à la Hulpe
  keywords: restaurant, la hulpe, genval, mazerine, take away, à emporter, sandwiches, business lunch, traiteur, snack, sandwicherie
hidden: true