logger:
  active: true
  display: false
  save_path: %site_path%/logs


template:
  cache: %site_path%/cache/templates
  debug: false
  strict: false
  path:
   - %site_path%/resources/views
   - %site_path%/resources/includes
   - %kernel_path%/Module
   - %kernel_path%/Resources/views
  extensions:
   - \Qwik\Kernel\Template\Extension\Translate
   - \Qwik\Kernel\Template\Extension\Locale
   - \Qwik\Kernel\Template\Extension\App

module:
  gallery:
    cache: true #cache des thumbnail. Si c'est mis à truc, le thumnail sera physiquement créé, sinon, on fera toujours du process php

  form:
    mail:
      redirect: false #redirection des mails toujours vers la même boite (pour debug, mettre un email)