
template: basic
title:
  fr: Réservation
  nl: Reservatie
  en: Reservation
meta:
  description:
    fr: BBSalve, Bed and Breakfast à Bruxelles
    nl: BBSalve, Bed and Breakfast in Brussel
    en: BBSalve, Bed and Breakfast in Brussels
  keywords:
    fr: bbsalve, bed and breakfast, maison d&#039;hôte, b&amp;b, bed, breakfast, Bruxelles, Auderghem, Ouderghem, Schuman, brussel, brussels
zones:
  zone1:
    text:
      module: html
      config:
        content:
          fr: |-
              <p>
                  Pour une r&eacute;servation, veuillez remplir le formulaire ci-dessous.<br />
                  Nous vous r&eacute;pondrons dans les plus brefs d&eacute;lais.</p>
          nl: |-
              <p>
                  Voor een reservatie nodigen wij u uit onderstaande formulier in te vullen.</p>
          en: |-
              <p>
                  For a reservation, we invite you to fill out the form below.</p>
    contact:
      module: form
      config:
        email: info@bbsalve.be
        language: fr
        fields:
          name:
            label:
              fr: Nom
              nl: Achernaam
              en: Surname
            required: 1
            type: text
          firstName:
            label:
              fr: Prénom
              nl: Naam
              en: First name
            required: 1
            type: text
          email:
            label:
              fr: E-mail
              nl: E-mail
              en: E-mail
            required: 1
            type: email
          address:
            label:
              fr: Adresse
              nl: Adresse
              en: Address
            required: 1
            type: textarea
          tel:
            label:
              fr: N° de téléphone
              nl: Tel
              en: Phone number
            required: 1
            type: text
          dateBegin:
            label:
              fr: Date d'arrivée
              nl: Aankomstdatum
              en: Arrival date
            required: 1
            type: date
          nights:
            label:
              fr: Nombre de nuit(s)
              nl: Aantal overnachtingen
              en: Number of nights
            required: 1
            type: text
          adults:
            label:
              fr: Nombre d'adulte(s)
              nl: Aantal volwassenen
              en: Number of adults
            required: 1
            type: text
          children:
            label:
              fr: Nombre d'enfant(s)
              nl: Aantal kinderen
              en: Number of children
            type: text
          questions:
            label:
              fr: Questions
              nl: Vragen
              en: Questions
            type: textarea
