
template: basic
title:
  fr: Erreur
  nl: Probleem
  en: Mistake
zones:
  zone1:
    text:
      module: html
      config:
        content:
          fr: Une erreur est survenue
          nl: Er is een fout opgetreden
          en: An error has occured